apiVersion: apps/v1
kind: Deployment
metadata:
  name: humi-deployment
  labels:
    app: humi
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: humi
  template:
    metadata:
      labels:
        app: humi
    spec:
      containers:
      - name: humi
        image: magnuscj/humi:prod_5
          #command: ["./start.sh"]
        ports:
          - containerPort: 80
            name: humi-cont-port
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "ls -l"]
          preStop:
             exec:
               command: ["/bin/bash","-c","ls -l"]
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - ./liveness.sh  
          initialDelaySeconds: 120
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: humi-ext-nordenort-service
spec:
  selector:
    app: humi
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: humi-cont-port
      nodePort: 30165

