apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue-deployment
  labels:
    app: hue
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: hue
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
      - name: hue
        image: magnuscj/hue:prod_1
          #command: ["./start.sh"]
        ports:
          - containerPort: 80
            name: hue-cont-port
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "ls -l"]
          preStop:
             exec:
               command: ["/bin/bash","-c","ls -l"]
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - ./liveness.sh  
          initialDelaySeconds: 120
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hue-ext-nordenort-service
spec:
  selector:
    app: hue
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: hue-cont-port
      nodePort: 30167

